const allergeni = {
    CarneBovina: [
      {
        nome: "Big Tasty / Big Tasty Bacon",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Big Mac",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cheeseburger/Doppio Cheeseburger",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Crispy McBacon / Gran Crispy McBacon / Gran Crispy McBacon Extra Bacon",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Crispy McWrap",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Double Burger BBQ",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "+",
        anidride: "+",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Gluten Free Burger",
        glutine: "",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "+",
        molluschi: "",
      },
      {
        nome: "Hamburger",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "!",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "My Selection Asiago DOP & Bacon",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "My Selection BBQ",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "!",
        sedano: "!",
        anidride: "+",
        senape: "+",
        lupini: "",
        molluschi: "!",
      },
      {
        nome: "Tasty McWrap",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      // Altri prodotti carne bovina
    ],
    CarneSuina: [
      {
        nome: "McMuffin Bacon & Egg",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McToast",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      // Altri prodotti carne suina
    ],
    Pollo: [
      {
        nome: "Chickenburger",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Chicken McNuggets",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Double Chicken BBQ",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "+",
        anidride: "+",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McChicken / Gran McChicken",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "!",
        uova: "+",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McWrap con petto di pollo croccante e Parmiggiano Reggiano",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "My Selection Pecorino Toscano DOP e Salsa Yuzu",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "+",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "My Selection Speck Alto Adige IGP & Salsa con Radicchio e Mela",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "+",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Spicy Nuggets",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      // Altri prodotti pollo
    ],
    Pesce: [
      {
        nome: "Filet-O-Fish",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "+",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      // Altri prodotti pesce
    ],
    Condimenti: [
      {
        nome: "Olio Extra Vergine di Oliva e Aceto Balsamico di Modena IGP / Olio Extravergine di Oliva e Aceto di Vino Bianco",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "+",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Agrodolce",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Barbecue",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Caesar salad",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: " Salsa Crispy McBacon",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "+",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Ketchup vaschetta  / Olio extra vergine di oliva / Salsa Piccante / Salsa Hot Devil",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Maionese vaschetta",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Salsa Senape piccante",
        glutine: "",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "+",
        lupini: "",
        molluschi: "",
      },
      // Altri prodotti condimenti
    ],
    Insalate: [
      {
        nome: "Grissini",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Insalata con petto di pollo croccante e Parmigiano Reggiano",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Insalata senza petto di pollo",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Sale iodato bustina / Pepe bustina / Insalata Mista / Insalata Verde con pomodori",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    PatatineFritte:[
      {
        nome: "Le Ricche Cheddar / Le Ricche Cheese & Bacon / Le Ricche Cheese Extra Bacon",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Patatine",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    FingerFood:[
      {
        nome: "Chicken Wings",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Panzerotti Con Pomodoro E Mozzarella 100% Italiani",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Pepite Asiago DOP & Speck Alto Adige IGP",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "!",
        crostacei: "",
        sedano: "!",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
    ],
    Bibite:[
      {
        nome: "Actimel",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Birra Peroni /Birra Peroni Gran Riserva Rossa/Birra Peroni Gran Riserva Puro Malto/Birra Peroni Non Filtrata",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Coca Cola / Coca Cola Zero /  Fanta / Sprite Zero / Spremuta d'arancia / Tè freddo al limone Zero / Tè freddo alla pesca Zero / Acqua minerale oligominerale naturale / Acqua minerale oligominerale naturale frizzante / Succo di mela biologico",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    Dessert:[
      {
        nome: "Cono",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Mela / Carotine Baby / Sciroppo per pancake / Ananas / Ciliegie / Pesca / Uva / Kiwi / Melone 100% Italiano",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McFlurry Baci / Sundae Baci",
        glutine: "",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McFlurry Oreo",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McFlurry Pistacchio",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McFlurry Smarties",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McFlurry Snickers",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "+",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McPops",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Milkshake Al Gusto Di Cioccolato",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: " Sundae affogato al Caramello / Sundae affogato al Cioccolato / Sundae al Fiordilatte / Milkshake Al Gusto Di Fragola / Sundae affogato al caffè / Snack di Parmigiano Reggiano / Sundae amarena / Milkshake Al Gusto Di Vaniglia / Milkshake Al Gusto Di Banana / Sundae Frutti Di Bosco",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Torta Cioccolato Multistrato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Torta Compleanno Fragola / Torta Di Compleanno Premium Alle Fragole",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Torta Compleanno Stracciatella",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Torta Di Compleanno Premium Al Cacao",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Pancakes",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    AreaCaffè:[
      {
        nome: "Brownies al Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Caffè Espresso / Caffè Espresso decaffeinato / Caffè Americano",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cappuccino / Cappuccino decaffeinato / Latte / Latte macchiato / Panna per caffè",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant al pistacchio",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "!",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Cacao",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Con Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant crema / Croissant vuoto / Croissant marmellata",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Donut cioccolato / Donut Zucchero",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Lemon Scented Tea / English Breakfast Tea / Earl Grey Tea / Pure Green Tea / Zucchero bustina / Zucchero di canna in bustina / Dolcificante / Miele d'acacia in bustina / The Caldo English Garden / Infuso Frutti Rossi / Infuso Zenzero E Limone / Camomilla",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McPops",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Succo di limone in bustina",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "+",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    McCafè:[
      {
        nome: "Bevanda A Base Di Soia / Cappuccino di Soia / Cappuccino di Soia Decaffeinato",
        glutine: "",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Brownies al Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Caffè al Ginseng",
        glutine: "!",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Caffè d'Orzo",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Caffè Espresso / Caffè Espresso decaffeinato / Caffè Americano /  Caffè shakerato classico",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cappuccino Ginseng",
        glutine: "!",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cappuccino Orzo",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cioccolata al Latte",
        glutine: "",
        soia: "+",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cheesecake Alle Fragole",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cheesecake Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant al pistacchio",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "!",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Cacao",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant cereali e frutti di bosco",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "+",
        latte: "!",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Con Nutella® ",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant crema / Croissant vuoto / Croissant marmellata",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Cupcake di Halloween",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Donut marshmallows ",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Donut zucchero / Donut Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "GelaTino",
        glutine: "!",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Latte / Latte macchiato / Panna per caffè / Panna spray (guarnitura torte, frappè, shake) / Topping cioccolato (guarnitura torte) / Crema al cioccolato bianco (guarnitura torte) / Cioccolata Fondente / Crema al caffè / Latte Alta Digeribilità",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Macaron Cioccolato UTZ",
        glutine: "!",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Macaron Lampone",
        glutine: "!",
        soia: "!",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "",
        latte: "!",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Macaron Pistacchio",
        glutine: "!",
        soia: "!",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McPops",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Mini donut cacao",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Mini donut zucchero",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Lemon Scented Tea / English Breakfast Tea / Earl Grey Tea / Pure Green Tea / Zucchero bustina / Zucchero di canna in bustina / Dolcificante / Spremuta d'arancia / Acqua minerale naturale / Acqua minerale naturale (aggiunta di anidride carbonica) / Miele d'acacia in bustina / Topping ai frutti di bosco (guarnitura torte) / The Caldo English Garden / Infuso Frutti Rossi / Infuso Zenzero E Limone /  Camomilla / Cacao in polvere / Cannella in polvere / Zucchero a velo / Succo Skipper Zuegg Ananas / Succo Skipper Zuegg Pesca senza zuccheri aggiunti / Skipper Zuegg Pera senza zuccheri aggiunti / Succo Skipper Zuegg ACE senza zuccheri aggiunti",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Succo di limone in bustina",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "+",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Tiramisù",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Torta Cioccolato Multistrato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],
    Colazione:[
      {
        nome: "Brownies al Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant al pistacchio",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "!",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Cacao",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant cereali e frutti di bosco",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "+",
        latte: "!",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant Con Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Croissant crema / Croissant vuoto / Croissant Marmellata ",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Donut zucchero / Donut Cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "!",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Latte / Latte macchiato / Caffè espresso macchiato / Caffè espresso decaffeinato macchiato / Panna per caffè / Cappuccino / Cappuccino decaffeinato / Marocchino / Actimel",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Limone in bustina",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "+",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: " Mela / Ananas / Sciroppo per pancake / Succo d'arancia / Caffè Espresso / Caffè Americano / Caffè Espresso decaffeinato / Lemon Scented Tea / English Breakfast Tea / Earl Grey Tea / Pure Green Tea / Tisana Limone e Zenzero / Zucchero in bustina / Zucchero di canna in bustina / Dolcificante / Miele d'acacia in bustina / Sciroppo vaniglia / Ciliegie / Pesca / Uva / Kiwi / Melone 100% Italiano ",
        glutine: "",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McMuffin Bacon & Egg",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McPops",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "McToast",
        glutine: "+",
        soia: "!",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin cioccolato",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "!",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Muffin Nutella®",
        glutine: "+",
        soia: "+",
        fruttaAGuscio: "+",
        arachidi: "!",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "!",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Pancake",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
      {
        nome: "Uova strapazzate / Uova strapazzate con bacon",
        glutine: "+",
        soia: "",
        fruttaAGuscio: "",
        arachidi: "",
        sesamo: "!",
        latte: "+",
        uova: "+",
        pesce: "",
        crostacei: "",
        sedano: "",
        anidride: "",
        senape: "",
        lupini: "",
        molluschi: "",
      },
    ],

  };
  